name: JupyterHealth SMART on FHIR test suite

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12] # extend if needed

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[testing]
    - name: Pull Docker image
    - run: docker pull smartonfhir/smart-launcher-2:latest
    - name: Run docker container 
    - run: docker run -d -p 8080:80 --name smart-launcher smartonfhir/smart-launcher-2:latest
    - name: Wait until ready
    - run: |
        until curl -s http://localhost:8080 > /dev/null; do
          echo "Waiting for container startup"
          sleep 5
        done
    - name: Run tests
      run: |
        pytest tests/

    